name: Production deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Set environment variables
        run: cp .env.dist .env.local
      - name: Start database
        run: supabase start
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm tests
