name: Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6
  run-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pnpm install
      - name: Check lint issue
        run: pnpm lint
      - name: Run unit test
        run: pnpm test
  prepare-deployment:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: pnpm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
  deploy-production:
    needs: [run-test, prepare-deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
